# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

# Deployment Groups

- id: primary-network-orchestrator-node
  type: group
  role: [primary-network-orchestrator-node]
  requires: [primary-controller, controller]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
    hosts, firewall, deploy_start]
  parameters:
    strategy:
      type: one_by_one

- id: network-orchestrator-node
  type: group
  role: [primary-network-orchestrator-node]
  requires: [primary-controller, controller, primary-network-orchestrator-node]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
    hosts, firewall, deploy_start]
  parameters:
    strategy:
      type: parallel

# Deployment Tasks
# No idea what purpose this hiera override task serves.
- id: network-orchestrator-pre-deployment-task
  type: puppet
  groups: [primary-controller, controller, primary-network-orchestrator-node, network-orchestrator-node]
  requires: [pre_deployment_start]
  required_for: [pre_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_pre_deployment.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-hiera-override
  type: puppet
  groups: [primary-controller, controller, primary-network-orchestrator-node, network-orchestrator-node]
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_hiera_override.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

# These tasks execute on the controller
- id: network-orchestrator-node-db-task
  type: puppet
  groups: [primary-controller]
  requires: [primary-database, database]
  required_for: [deploy_end]
  cross-depends:
    - name: /(primary-)?database/
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_db.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-astara-neutron-install-task
  type: puppet
  role: [primary-controller, controller]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_astara_neutron_install.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-astara-neutron-configure-task
  type: shell
  role: [primary-controller, controller]
  requires: [network-orchestrator-node-astara-neutron-install-task]
  required_for: [post_deployment_end]
  parameters:
    cmd: ./scripts/controller_post_deploy.sh
    timeout: 1800

# These tasks execute on the astara node
- id: network-orchestrator-node-install-task
  type: puppet
  groups: [primary-network-orchestrator-node, network-orchestrator-node]
  requires: [network-orchestrator-hiera-override, netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_install.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-ml2-task
  type: puppet
  groups: [primary-network-orchestrator-node, network-orchestrator-node]
  requires: [network-orchestrator-node-install-task]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openstack-network/plugins/ml2.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-ml2-config-task
  type: puppet
  groups: [primary-network-orchestrator-node, network-orchestrator-node]
  requires: [network-orchestrator-node-ml2-task]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openstack-network/common-config.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-configure-task
  type: puppet
  groups: [primary-network-orchestrator-node, network-orchestrator-node]
  requires: [network-orchestrator-node-install-task, network-orchestrator-node-ml2-task]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_configure.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-image-task
  type: puppet
  groups: [primary-network-orchestrator-node]
  requires: [network-orchestrator-node-install-task]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_image.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 3800

- id: network-orchestrator-node-create-resources-task
  type: puppet
  groups: [primary-network-orchestrator-node, network-orchestrator-node]
  requires: [network-orchestrator-node-configure-task]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/network_orchestrator_create_resources.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 1800

- id: network-orchestrator-node-post-deployment-task
  type: shell
  role: [primary-network-orchestrator-node, network-orchestrator-node]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    cmd: ./scripts/astara_post_deploy.sh
    timeout: 1800

